Repository pagopa/pagopa-api-config-cache, pull requests merged in 2024-05, with the labels that each got.

#60 [NOD-855] Deploy dev for Nexi Postgres
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/release_deploy.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/04_apim_api.tf
  infra/04_apim_api_oracle.tf
  infra/04_apim_api_postgres_nexi.tf
  openapi/openapi.json
  openapi/openapi_export.json
  openapi/openapi_fdrv1.json
  openapi/openapi_nodev1.json
  openapi/openapi_standinv1.json
  openapi/openapi_verifierv1.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/Application.java
  src/main/java/it/gov/pagopa/apiconfig/cache/controller/HomeController.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/apiconfig/cache/OpenApiGenerationTest.java
  src/test/resources/application.properties
Labels: size/large, patch

#62 NOD-828
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_export.json
  openapi/openapi_fdrv1.json
  openapi/openapi_nodev1.json
  openapi/openapi_standinv1.json
  openapi/openapi_verifierv1.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/cache/model/node/v1/creditorinstitution/Station.java
  src/main/java/it/gov/pagopa/apiconfig/cache/model/node/v1/psp/Channel.java
  src/main/java/it/gov/pagopa/apiconfig/cache/util/mapper/ConvertCanaliToChannelDetails.java
  src/main/java/it/gov/pagopa/apiconfig/cache/util/mapper/ConvertStazioniToStationDetails.java
Labels: size/large

#63 [NOD-895] Fix helm in UAT
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_export.json
  openapi/openapi_fdrv1.json
  openapi/openapi_nodev1.json
  openapi/openapi_standinv1.json
  openapi/openapi_verifierv1.json
  pom.xml
Labels: size/small

#64 chore: Migrazione redis multiAZ
  helm/neu-dev/values-dev.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  helm/weu-it/values-it.yaml
  helm/weu-prf/values-prf.yaml
Labels: size/small, patch

#66 fix: [NOD-911] Product-api relationship
  infra/04_apim_api.tf
  infra/04_apim_api_oracle.tf
  infra/99_locals.tf
Labels: size/small, ignore-for-release

#67 Fix prod pipeline
  .github/workflows/deploy_with_github_runner.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_export.json
  openapi/openapi_fdrv1.json
  openapi/openapi_nodev1.json
  openapi/openapi_standinv1.json
  openapi/openapi_verifierv1.json
  pom.xml
Labels: patch
