Repository pagopa/pagopa-api-config-cache, pull requests merged in 2024-04, with the labels that each got.

#53 Export api cfg cache
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/04_apim_export.tf
  infra/99_locals.tf
Labels: size/small

#54 Export API CFG Cache
  .github/workflows/deploy_with_github_runner.yml
  helm/values-uat.yaml
  infra/04_apim_api.tf
Labels: size/small, patch

#55 fix helm chart prod
  helm/Chart.yaml
  helm/values-prod.yaml
Labels: size/small

#56 fix full key for informations
  openapi/openapi.json
  openapi/openapi_export.json
  openapi/openapi_fdrv1.json
  openapi/openapi_nodev1.json
  openapi/openapi_standinv1.json
  openapi/openapi_verifierv1.json
  src/main/java/it/gov/pagopa/apiconfig/cache/controller/CacheController.java
  src/main/java/it/gov/pagopa/apiconfig/cache/controller/RefreshController.java
  src/main/java/it/gov/pagopa/apiconfig/cache/controller/stakeholders/FdrCacheController.java
  src/main/java/it/gov/pagopa/apiconfig/cache/controller/stakeholders/NodeCacheController.java
  src/main/java/it/gov/pagopa/apiconfig/cache/controller/stakeholders/StandInCacheController.java
  src/main/java/it/gov/pagopa/apiconfig/cache/service/CacheEventHubService.java
  src/main/java/it/gov/pagopa/apiconfig/cache/service/ConfigService.java
  src/main/java/it/gov/pagopa/apiconfig/cache/util/Constants.java
  src/test/java/it/gov/pagopa/apiconfig/cache/NodoConfigCacheTest.java
  src/test/java/it/gov/pagopa/apiconfig/cache/RedisTest.java
  src/test/java/it/gov/pagopa/apiconfig/cache/controller/CacheNotInitializedTest.java
  src/test/java/it/gov/pagopa/apiconfig/cache/controller/ControllerTest.java
Labels: size/large

#57 fix base64 encoder
  src/main/java/it/gov/pagopa/apiconfig/cache/service/ConfigService.java
  src/main/java/it/gov/pagopa/apiconfig/cache/util/Constants.java
  src/test/java/it/gov/pagopa/apiconfig/cache/VerifierTest.java
Labels: size/small

#61 feat: Added terraform.sh action
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/release_deploy.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/.terraform-version
  infra/.terraform.lock.hcl
  infra/04_apim_api.tf
  infra/04_apim_export.tf
  infra/99_main.tf
  openapi/openapi.json
  openapi/openapi_export.json
  openapi/openapi_fdrv1.json
  openapi/openapi_nodev1.json
  openapi/openapi_standinv1.json
  openapi/openapi_verifierv1.json
  pom.xml
Labels: size/small, ignore-for-release
