Repository pagopa/pagopa-api-config-cache, pull requests merged in 2025-05, with the labels that each got.

#82 fix: bug elaborateStandInCache
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_export.json
  openapi/openapi_fdrv1.json
  openapi/openapi_nodev1.json
  openapi/openapi_standinv1.json
  openapi/openapi_verifierv1.json
  openapi/openapi_wispv1.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/cache/service/StakeholderConfigService.java
Labels: size/small

#84 chore: Change hikariCP cfg
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_export.json
  openapi/openapi_fdrv1.json
  openapi/openapi_nodev1.json
  openapi/openapi_standinv1.json
  openapi/openapi_verifierv1.json
  openapi/openapi_wispv1.json
  pom.xml
  src/main/resources/application.properties
Labels: size/small, patch

#83 Pidm 487 apiconfig wl identity helm v 7 5 0
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/release_deploy.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: enhancement

#86 chore: disabled postgres Nexi dev
  helm/values-dev.yaml
  infra/04_apim_api_postgres_nexi.tf
Labels: size/small

#87 chore: workload identity for cronjob
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  openapi/openapi_export.json
  openapi/openapi_fdrv1.json
  openapi/openapi_nodev1.json
  openapi/openapi_standinv1.json
  openapi/openapi_verifierv1.json
  openapi/openapi_wispv1.json
  pom.xml
Labels: size/small

#88 Workload cron job
  .github/workflows/deploy_with_github_runner.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
Labels: size/small
